package:
  name: hello
  version: {{environ.get('GIT_DESCRIBE_TAG', 'v0.1')}}
  #version: {{environ.get('GIT_DESCRIBE_TAG', '')}}

source:
  path: ../

build:
  number: {{environ.get('GIT_DESCRIBE_NUMBER', 0)}}
  script: python setup.py install
  noarch_python: True
  entry_points:
    - hello = hello:cli

requirements:
  build:
    - python

  run:
    - python

about:
  home: https://github.com/sandhujasmine/CondaWorkshop/simple_recipe
  summary: "hello is a very simple example of conda-build"
